### ISSUE TITLE
The program wont work MX Linux

### ISSUE THREAD

**Issue by Mak3yrM0v3** [CameronLonsdale/MTP#17]
I install the program and the console give me these response:
Collecting mtp
  Using cached https://files.pythonhosted.org/packages/e0/e2/fc1ba4e5aa4dd2b6c76d62bdd1cc484e2fd3e3eb9fc2115939176aa07bcc/mtp-1.0.0.tar.gz
Requirement already satisfied: urwid==2.0.1 in ./.local/lib/python2.7/site-packages (from mtp) (2.0.1)
Building wheels for collected packages: mtp
  Running setup.py bdist_wheel for mtp ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-gBxvxi/mtp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-xTK6Zz --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for mtp
  Running setup.py clean for mtp
Failed to build mtp
Installing collected packages: mtp
  Running setup.py install for mtp ... done
Successfully installed mtp-1.0.0

**Comment by CameronLonsdale** [comment]
Hey @Mak3yrM0v3 , looks like you might be using Python 2.7. MTP only works for python 3.7 and newer. Try using a virtual environment when installing and see if that makes a difference. Or use pip3 install mtp
